Use Olist_Project;
/* PROJECT : E-COMMERCE ANALYTICS
AUTHOR  : Priyanka Gurugubelli
TOOLS   : SQL Server Management Studio
DATABASE: Olist_Project

This project analyzes customer behavior, sales performance,
delivery efficiency, payment trends, and seller performance*/


/*SECTION 1 : DATABASE OVERVIEW*/
SELECT
(SELECT COUNT(*) FROM Orders) AS Total_Orders,
(SELECT COUNT(DISTINCT customer_unique_id) FROM Customers) AS Total_Customers,
(SELECT COUNT(DISTINCT seller_id) FROM Sellers) AS Total_Sellers,
(SELECT SUM(payment_value) FROM Order_Payments) AS Total_Revenue,
(SELECT AVG(CAST(review_score AS FLOAT)) FROM Order_Reviews) AS Avg_Rating;
--Total Customers
SELECT COUNT(DISTINCT customer_unique_id) AS Total_Customers
FROM Customers;
GO

--Total Orders
SELECT COUNT(*) AS Total_Orders
FROM orders;
GO

--Total Sellers
SELECT COUNT(DISTINCT seller_id) AS Total_Sellers
FROM sellers;
GO

--Total Products
SELECT COUNT(DISTINCT product_id) AS Total_Products
FROM products;
GO

--Total Orders
SELECT
order_status,
COUNT(*) AS Orders
FROM orders
GROUP BY order_status
ORDER BY Orders DESC;
GO

/*SECTION 2 : SALES ANALYSIS*/

/*Total revenue generated by the platform
Here,
Revenue is the primary KPI to evaluate business performance*/

--Total revenue
SELECT
    SUM(payment_value) AS Total_Revenue
FROM order_payments;
GO

Insight:Measures overall business performance

--Monthly Revenue Trend
SELECT
YEAR(order_purchase_timestamp) AS Order_Year,
MONTH(order_purchase_timestamp) AS Order_Month,
SUM(payment_value) AS Revenue
FROM orders o
JOIN order_payments op
ON o.order_id=op.order_id
GROUP BY
YEAR(order_purchase_timestamp),
MONTH(order_purchase_timestamp)
ORDER BY
Order_Year,
Order_Month;
GO

Insight:Shows revenue growth and seasonal trends

--Average Order Month
SELECT
SUM(payment_value)/
COUNT(DISTINCT order_id) AS Average_Order_Value
FROM order_payments;
GO

Insight:Indicates average customer spending per order

--Top Categories of Revenue
SELECT
p.product_category_name,
SUM(oi.price) AS Revenue
FROM order_items oi
JOIN products p
ON oi.product_id=p.product_id
GROUP BY p.product_category_name
ORDER BY Revenue DESC;
GO

Insight:Shows which product categories generate the highest revenue

--Lowest Revenue Categories
SELECT TOP 10
p.product_category_name,
SUM(oi.price) AS Revenue
FROM order_items oi
JOIN products p
ON oi.product_id=p.product_id
GROUP BY p.product_category_name
ORDER BY Revenue ASC;
GO

Insight:Identifies underperforming categories

--Top Products By Revenue
SELECT TOP 10
product_id,
SUM(price) AS Revenue
FROM order_items
GROUP BY product_id
ORDER BY Revenue DESC;
GO

Insight:Reveals the best-selling products

/* CUSTOMER ANALYSIS*/
--Customer Distribution by State
SELECT

customer_state,

COUNT(*) AS Customers

FROM customers

GROUP BY customer_state

ORDER BY Customers DESC;
GO

Insight:Customer concentration is highest in a few states, indicating key markets for sales and marketing efforts

--Top Customers
SELECT TOP 10
c.customer_unique_id,
SUM(op.payment_value) AS Total_Spent
FROM customers c
JOIN orders o
ON c.customer_id=o.customer_id
JOIN order_payments op
ON o.order_id=op.order_id
GROUP BY c.customer_unique_id
ORDER BY Total_Spent DESC;
GO

Insight:A small group of customers contributes significantly to revenue, highlighting the importance of customer retention

--Customer Spending On Average
SELECT
AVG(payment_value) AS Avg_Customer_Spending
FROM order_payments;
GO

Insights:The average customer spending provides a benchmark for evaluating purchasing behavior and future sales strategies

--Customers Per City
SELECT TOP 10
customer_city,
COUNT(*) AS Customers
FROM customers
GROUP BY customer_city
ORDER BY Customers DESC;
GO

Insight:Major cities account for a larger share of customers, presenting opportunities for region-specific campaigns

--First 10 Orders With Customer City
SELECT TOP 10
o.order_id,
c.customer_city,
o.order_purchase_timestamp
FROM orders o
JOIN customers c
ON o.customer_id=c.customer_id;
GO

Insight:Linking customer locations with orders helps analyze geographical purchasing patterns

/*PRODUCT ANALYSIS*/
--Products By Category
SELECT
    product_category_name,
    COUNT(product_id) AS Total_Products
FROM products
GROUP BY product_category_name
ORDER BY Total_Products DESC;
GO

Insight:Some categories have a much larger product assortment than others, indicating greater product availability

--Average Product Price By Category
SELECT
    p.product_category_name,
    AVG(oi.price) AS Avg_Product_Price
FROM products p
JOIN order_items oi
ON p.product_id = oi.product_id
GROUP BY p.product_category_name
ORDER BY Avg_Product_Price DESC;
GO

Insight:Product prices vary across categories, helping identify premium and budget segments

--Top 10 Expensive Products Sold
SELECT TOP 10
    product_id,
    MAX(price) AS Highest_Price
FROM order_items
GROUP BY product_id
ORDER BY Highest_Price DESC;
GO

Insight:High-value products contribute significantly to revenue despite lower sales volume

--Lowest Products Sold
SELECT TOP 10
    product_id,
    MIN(price) AS Lowest_Price
FROM order_items
GROUP BY product_id
ORDER BY Lowest_Price ASC;
GO

Insight:Low-priced products attract price-sensitive customers and increase order volume

--Revenue Contribution By Category
SELECT
    p.product_category_name,
    SUM(oi.price) AS Revenue,
    ROUND(
        SUM(oi.price)*100.0 /
        SUM(SUM(oi.price)) OVER(),
        2
    ) AS Revenue_Percentage
FROM order_items oi
JOIN products p
ON oi.product_id=p.product_id
GROUP BY p.product_category_name
ORDER BY Revenue DESC;
GO

Insight:A few product categories generate the majority of total revenue, making them critical business drivers

/*SELLER ANALYSIS*/
--Top 10 Sellers By Category
SELECT TOP 10
    seller_id,
    SUM(price) AS Revenue
FROM order_items
GROUP BY seller_id
ORDER BY Revenue DESC;
GO

Insight:Top-performing sellers contribute a major share of marketplace revenue

--Bottom Sellers
SELECT TOP 10
    seller_id,
    SUM(price) AS Revenue
FROM order_items
GROUP BY seller_id
ORDER BY Revenue ASC;
GO

Insight:Some sellers generate minimal revenue, indicating opportunities for performance improvement


--Average Revenue Per Seller
SELECT
    AVG(SellerRevenue) AS Avg_Seller_Revenue
FROM
(
    SELECT
        seller_id,
        SUM(price) AS SellerRevenue
    FROM order_items
    GROUP BY seller_id
) A;
GO

Insight:Average seller revenue serves as a benchmark for evaluating seller performance


/*DELIVERY ANALYSIS*/
--Average Delivery Time
SELECT
AVG(DATEDIFF(day,
order_purchase_timestamp,
order_delivered_customer_date))
AS Avg_Delivery_Days
FROM orders
WHERE order_status='delivered';
GO

Insight:Average delivery time reflects the overall efficiency of the logistics network

--Fastest Delivered Orders
SELECT TOP 10
order_id,
DATEDIFF(day,
order_purchase_timestamp,
order_delivered_customer_date)
AS Delivery_Days
FROM orders
WHERE order_status='delivered'
ORDER BY Delivery_Days;
GO

Insight:Fast deliveries improve customer satisfaction and enhance the shopping experience

--Delayed Deliveries
SELECT TOP 10
order_id,
DATEDIFF(day,
order_estimated_delivery_date,
order_delivered_customer_date)
AS Delay_Days
FROM orders
WHERE order_delivered_customer_date >
order_estimated_delivery_date
ORDER BY Delay_Days DESC;
GO	

Insight:Delayed deliveries may negatively impact customer satisfaction and review scores

--Delivery time By State
SELECT
c.customer_state,
AVG(DATEDIFF(day,
o.order_purchase_timestamp,
o.order_delivered_customer_date))
AS Avg_Delivery_Days
FROM customers c
JOIN orders o
ON c.customer_id=o.customer_id
WHERE o.order_status='delivered'
GROUP BY c.customer_state
ORDER BY Avg_Delivery_Days DESC;
GO

Insight:Delivery performance varies by state, highlighting regions that may require logistics improvements


/*PAYMENT ANALYSIS*/
--Payment Method Distribution
SELECT
payment_type,
COUNT(*) AS Total_Transactions
FROM order_payments
GROUP BY payment_type
ORDER BY Total_Transactions DESC;
GO

Insight:Customers show a clear preference for certain payment methods over others

--Installment Analysis
SELECT
payment_installments,
COUNT(*) AS Orders
FROM order_payments
GROUP BY payment_installments
ORDER BY payment_installments;
GO

Insight:Installment payments indicate customers preference for flexible purchasing options


/*REVIEW ANALYSIS*/
--Average Review Score
SELECT
AVG(CAST(review_score AS FLOAT))
AS Average_Rating
FROM order_reviews;
GO

--Different Categories With Lowest Average Ratings
SELECT TOP 10
p.product_category_name,
AVG(CAST(r.review_score AS FLOAT)) AS Avg_Rating
FROM products p
JOIN order_items oi
ON p.product_id=oi.product_id
JOIN order_reviews r
ON oi.order_id=r.order_id
GROUP BY p.product_category_name
ORDER BY Avg_Rating ASC;
GO

--Sellers Above Average Revenue(CTE)
WITH SellerRevenue AS
(
    SELECT
        seller_id,
        SUM(price) AS Revenue
    FROM order_items
    GROUP BY seller_id
)

SELECT *
FROM SellerRevenue
WHERE Revenue >
(
    SELECT AVG(Revenue)
    FROM SellerRevenue
	);
GO

Insight:Sellers exceeding the average revenue represent the marketplaces top-performing businesses.

--Revenue Ranking Using DENSE RANK
SELECT
seller_id,
SUM(price) AS Revenue,
DENSE_RANK() OVER(
ORDER BY SUM(price) DESC
) AS Revenue_Rank
FROM order_items
GROUP BY seller_id;
GO

Insight:
--Delivery Performance Classification
SELECT
order_id,
DATEDIFF(day,
order_purchase_timestamp,
order_delivered_customer_date)
AS Delivery_Days,
CASE
WHEN DATEDIFF(day,
order_purchase_timestamp,
order_delivered_customer_date) <=3
THEN 'Fast'

WHEN DATEDIFF(day,
order_purchase_timestamp,
order_delivered_customer_date) <=7
THEN 'Normal'

ELSE 'Delayed'

END AS Delivery_Status
FROM orders
WHERE order_status='delivered';
GO

Insight:Categorizing deliveries into Fast, Normal, and Delayed simplifies logistics performance monitoring

--Monthly SaLes View
CREATE VIEW Monthly_Sales AS
SELECT
YEAR(o.order_purchase_timestamp) AS Sales_Year,
MONTH(o.order_purchase_timestamp) AS Sales_Month,
SUM(op.payment_value) AS Revenue
FROM orders o
JOIN order_payments op
ON o.order_id=op.order_id
GROUP BY
YEAR(o.order_purchase_timestamp),
MONTH(o.order_purchase_timestamp);
GO

Insight:The monthly sales summary provides a consolidated view of revenue trends over time

--Running Revenue Trend
SELECT
Sales_Year,
Sales_Month,
Revenue,
SUM(Revenue) OVER(
ORDER BY Sales_Year, Sales_Month
) AS Running_Revenue
FROM Monthly_Sales;
GO

Insight:Running revenue highlights cumulative business growth and long-term sales performance
SELECT
    payment_type,
    COUNT(DISTINCT order_id) AS Total_Orders,
    SUM(payment_value) AS Total_Revenue,
    AVG(payment_value) AS Avg_Payment_Value
FROM order_payments
GROUP BY payment_type
ORDER BY Total_Revenue DESC;
GO